site_name: Calculation Docs

theme:
  name: material
  custom_dir: overrides

plugins:
  - mkdocstrings
  - search

extra:
  version:
    provider: mike

nav:
  - Calculation Docs 2: index.md
  - tutorials.md
  - How-To Guides: how-to-guides.md
  - reference.md
  - explanation.md
