site_name: Calculation Docs
site_url: https://arcook-intel.github.io/LearnDocumentation/

# Repository
repo_url: https://github.com/arcook-intel/LearnDocumentation/
edit_uri: 'edit/main/docs/'

theme:
  name: material
  custom_dir: overrides

plugins:
  - mkdocstrings
  - search

extra:
  version:
    provider: mike
